spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/campus_recruitment?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  redis:
#    host: 82.157.42.25
#    port: 6379
#    password: Redis123

  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.qq.com
    port: 587
    username: 1459579638@qq.com
    password: fmsvxkniyoqghibd
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 3030

file:
  upload:
    path: ./uploads/resumes/
  remote-upload:
    url: http://82.157.42.25:5050/file/upload

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  枚举类包路径
application:
  security:
    secret: mySecretKeyForJWTTokenGenerationAndValidationInCampusRecruitmentSystem2024
  enum:
    default:
      package:
        path: com.caohao.common.enums.impl
